name: CI

on:
  pull_request:
  push:
    branches:
    - "main"

jobs:
  lint:
    name: Go lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # renovate: tag=v3.0.2
      - uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # renovate: tag=v3.1.0
        with:
          go-version: 1.18
      - uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc # renovate: tag=v3.2.0
        with:
          # renovate: datasource=github-tags depName=golangci/golangci-lint versioning=semver
          version: v1.46.2

  test:
    name: Go test & coverage
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # renovate: tag=v3.0.2
        with:
          fetch-depth: 2 # See https://community.codecov.com/t/issue-detecting-commit-sha-please-run-actions-checkout-with-fetch-depth-1-or-set-to-0/2571
      - uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # renovate: tag=v3.1.0
        with:
          go-version: 1.18
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
