name: CI

on:
  pull_request:
  push:
    branches:
    - "main"

jobs:
  lint:
    name: Go lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # tag=v3.3.1
        with:
          # renovate: datasource=golang-versions depName=golang/go versioning=semver
          go-version: 1.19.0
      - uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # v3.3.1
        with:
          # renovate: datasource=github-tags depName=golangci/golangci-lint versioning=semver
          version: v1.50.1

  test:
    name: Go test & coverage
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          fetch-depth: 2 # See https://community.codecov.com/t/issue-detecting-commit-sha-please-run-actions-checkout-with-fetch-depth-1-or-set-to-0/2571
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # tag=v3.3.1
        with:
          # renovate: datasource=golang-versions depName=golang/go versioning=semver
          go-version: 1.19.0
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
